---
- name: Create Ansible folder
  hosts: all
  become: true

  tasks:
    - name: Create ansible directory
      ansible.builtin.file:
        path: /tmp/ansible
        state: directory
        mode: '0755'
