---
- name: Create Ansible folder
  hosts: localhost
  become: true

- name: check env
  shell: set
  register: cmd_out

- debug:
    msg: "{{ cmd_out }}"

  tasks:
    - name: Create ansible directory
      ansible.builtin.file:
        path: /tmp/ansible2
        state: directory
        mode: '0755'
