---
- name: Create Ansible folder
  hosts: localhost
    #  become: true

  tasks:
    #    - name: check env
    #      shell: set
    #      register: cmd_out

    - debug:
        msg: "{{ ssh_pubkey }}, {{ ssh_privkey }}, {{ pull_secret }}, {{ vcenter_uid }}, {{ vcenter_pass }}, {{ vcenter_cacert }}

          #    - name: Create ansible directory
          #      ansible.builtin.file:
          #        path: /tmp/ansible2
          #        state: directory
          #        mode: '0755'
